version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - sudo apt-get update && apt-get install unzip
      - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
      - unzip terraform_0.11.10_linux_amd64.zip
      - sudo mv terraform /usr/local/bin/
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - cd terraform_modules
      - terraform init
      - terrform plan  
      - terraform apply -auto-approve
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths